# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca42efddf1af2411897d664cb72c48c57c9faf5f574dd50b9a1622e0713424212dfb0cbad0394b0511cad7bbde462df520b71d98ef3c5da8c8b344ed82e3fe5e

test:
  secret_key_base: 230b0df78b37c85ee4d18febf3c57d014aa93c7e6a7a39524cb7a5931f7f5ea3777124bf2cdfa52a88e718f0c929179783c2dd92141a1646fc88938626c0c2f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
